USE DATABASE DWH_prod;
USE SCHEMA APLsdb;



SELECT  
        CO.COMPANY_CODE_PIS
        ,CO.COMPANY_CODE
        ,CO.NAME COMPANY_NAME
        ,T.DATE_SID ACCOUNTING_DATE_SID
 --popravek 6.4.          
        ,dat.ext_refr ACCOUNTING_DATE
--        ,dat.date_sid ACCOUNTING_DATE_sid        
 --popravek 6.4.  
        ,T44.PROFIT_CENTER_EXT_REFR 
        ,T44.PROFIT_CENTER_NAME
        ,NULL AS CUSTOMER_TYPE_CODE
        ,NULL AS CUSTOMER_TYPE
        ,T.IS_OWN_USAGE
        ,NULL AS PAYMENT_METHOD       
        ,PR.PRODUCT_CODE 
        ,PR.PRODUCT_NAME_SHORT 
        ,T44.LEVEL01_EXT_REFR PC_LEVEL01_EXT_REFR        
        ,T44.LEVEL02_EXT_REFR PC_LEVEL02_EXT_REFR      
        ,T44.LEVEL03_EXT_REFR PC_LEVEL03_EXT_REFR        
        , T44.LEVEL04_EXT_REFR PC_LEVEL04_EXT_REFR
        ,T44.LEVEL05_EXT_REFR PC_LEVEL05_EXT_REFR        
        ,T44.LEVEL06_EXT_REFR PC_LEVEL06_EXT_REFR      
        ,T44.LEVEL07_EXT_REFR PC_LEVEL07_EXT_REFR         
        ,T44.LEVEL08_EXT_REFR PC_LEVEL08_EXT_REFR
        ,T44.LEVEL09_EXT_REFR PC_LEVEL09_EXT_REFR        
        ,T44.LEVEL10_EXT_REFR PC_LEVEL10_EXT_REFR
        ,T44.LEVEL01_CODE PCL1       
        ,T44.LEVEL01_NAME PC_L1_NAME 
        ,T44.LEVEL02_CODE PC_L2      
        , T44.LEVEL02_NAME PC_L2_NAME      
        ,T44.LEVEL03_CODE PC_L3        
        ,T44.LEVEL03_NAME PC_L3_NAME        
        ,T44.LEVEL04_CODE PC_L4      
        ,T44.LEVEL04_NAME PC_L4_NAME 
        ,T44.LEVEL05_CODE PC_L5      
        ,T44.LEVEL05_NAME PC_L5_NAME
        ,T44.LEVEL06_CODE PC_L6      
        ,T44.LEVEL06_NAME PC_L6_NAME 
        ,T44.LEVEL07_CODE PC_L7      
        , T44.LEVEL07_NAME PC_L7_NAME      
        ,T44.LEVEL08_CODE PC_L8        
        ,T44.LEVEL08_NAME PC_L8_NAME        
        ,T44.LEVEL09_CODE PC_L9      
        ,T44.LEVEL09_NAME PC_L9_NAME 
        ,T44.LEVEL10_CODE PC_L10     
        ,T44.LEVEL10_NAME PC_L10_NAME         
        ,PR.LEVEL01_CODE PR_L1        
        ,PR.LEVEL01_NAME PR_L1_NAME       
        ,PR.LEVEL02_CODE PR_L2          
        ,PR.LEVEL02_NAME PR_L2_NAME             
        ,PR.LEVEL03_CODE PR_L3          
        ,PR.LEVEL03_NAME PR_L3_NAME             
        ,PR.LEVEL04_CODE PR_L4          
        ,PR.LEVEL04_NAME PR_L4_NAME     
        ,PR.LEVEL05_CODE PR_L5          
        ,PR.LEVEL05_NAME PR_L5_NAME
        ,PR.LEVEL06_CODE PR_L6        
        ,PR.LEVEL06_NAME PR_L6_NAME      
		,PR.LEVEL07_CODE PR_L7          
		,PR.LEVEL07_NAME PR_L7_NAME             
		,PR.LEVEL08_CODE PR_L8          
		,PR.LEVEL08_NAME PR_L8_NAME             
		,PR.LEVEL09_CODE PR_L9          
		,PR.LEVEL09_NAME PR_L9_NAME     
		,PR.LEVEL10_CODE PR_L10         
		,PR.LEVEL10_NAME PR_L10_NAME
        ,0 AS SALES_LINE_QTY_AC
        ,0 AS SALES_LINE_QTY_KG_AC
        ,0 AS SALES_LINE_QTY_L_AC
        ,0 AS SALES_LINE_QTY_KWH_AC
        ,0 AS SALES_LINE_QTY_SM3_AC
        ,0 AS NET_SALES_LINE_AMT_AC  
        ,0 AS NET_MARGIN_LINE_AMT_AC
        ,0 AS NET_SALES_LINE_AMT_EUR_AC
        ,0 AS NET_MARGIN_LINE_AMT_EUR_AC    
            
        ,0 AS SALES_LINE_QTY_PY
        ,0 AS SALES_LINE_QTY_KG_PY
        ,0 AS SALES_LINE_QTY_L_PY
        ,0 AS SALES_LINE_QTY_KWH_PY
        ,0 AS SALES_LINE_QTY_SM3_PY
        ,0 AS NET_SALES_LINE_AMT_PY  
        ,0 AS NET_MARGIN_LINE_AMT_PY
        ,0 AS NET_SALES_LINE_AMT_EUR_PY
        ,0 AS NET_MARGIN_LINE_AMT_EUR_PY  
        /* to be devided on BU and BU_py  */      
        ,CAST(ROUND(SALES_LINE_QTY, 3) AS DECIMAL(30,3)) AS SALES_LINE_QTY_BU
        ,CAST(ROUND(SALES_LINE_QTY_KG, 3) AS DECIMAL(30,3)) AS SALES_LINE_QTY_KG_BU
        ,CAST(ROUND(SALES_LINE_QTY_LITER, 3) AS DECIMAL(30,3)) AS SALES_LINE_QTY_L_BU
        ,CAST(ROUND(SALES_LINE_QTY_KWH, 3) AS DECIMAL(30,3)) AS SALES_LINE_QTY_KWH_BU
        ,CAST(ROUND(SALES_LINE_QTY_SM3, 3) AS DECIMAL(30,3)) AS SALES_LINE_QTY_SM3_BU
        ,CAST(ROUND(NET_SALES_LINE_AMT, 6) AS DECIMAL(30,6)) AS NET_SALES_LINE_AMT_BU  
        ,CAST(ROUND(MARGIN_LINE_AMT, 6) AS DECIMAL(30,6)) AS MARGIN_LINE_AMT_BU
        ,CAST(ROUND(NET_SALES_LINE_AMT*ER.EXCHANGE_RATE_FLOAT, 6) AS DECIMAL(30,6)) AS NET_SALES_LINE_AMT_EUR_BU
        ,CAST(ROUND(MARGIN_LINE_AMT*ER.EXCHANGE_RATE_FLOAT, 6) AS DECIMAL(30,6)) AS NET_MARGIN_LINE_AMT_EUR_BU    
        ,3 AS PPN_SRC
FROM 
	APLSDB.F_SALES_PLAN_DAILY T
----------------COMPANY----------------------------------------------------
 --popravek 6.4.    
left join D_Date dat on dat.DATE_SID=t.ACCOUNTING_DATE_SID
left join D_Date datx on datx.month_id=dat.month_id and datx.day_of_month = 1
 --popravek 6.4.    

INNER JOIN 
	APLSDB.D_COMPANY CO 
		ON CO.COMPANY_SID=T.COMPANY_SID  --AND CO.VLD_TO_DT='9999-12-31 00:00:00'
-----------------PROFITNI CENTRI---------------------------------------------
INNER JOIN  
	APLSDB.V_PROFIT_CENTER_BI T44               
		ON  T.PROFIT_CENTER_SID  = T44.PROFIT_CENTER_SID     
		AND T44.HIERARCHY_EXT_REFR = 'PC|STD_SAP_PIS' 
 --------------PRODUKTI----------------------------------------------------------
INNER JOIN       
	APLSDB.V_PRODUCT_BI PR                
		ON  T.PRODUCT_SID = PR.PRODUCT_SID 
		AND PR.HIERARCHY_EXT_REFR = 'PR|SAP' -- -- 'PR|PIS'                         
--------------------PLA?EVANJE----------------------------------------------------------------------
LEFT JOIN
	APLSDB.D_EXCHANGE_RATE ER 
		ON T.CURRENCY_SID = ER.CURRENCY_FROM_SID 
		AND ER.CURRENCY_TO_EXT_REFR ='EUR' 
		AND ER.EXCHANGE_RATE_TYPE_EXT_REFR = 'PLN D' 
		AND CAST(TO_VARCHAR(ER.EFF_TO_DT, 'YYYYMMDD')  AS INTEGER ) = T.DATE_SID 
		AND CO.COUNTRY_SID=ER.COUNTRY_SID --AND CO.COUNTRY_EXT_REFR=ER.COUNTRY_EXT_REFR
--INNER JOIN D_PAYMENT_METHOD_HIERARCHY PM ON T.PAYMENT_METHOD_SID=PM.PAYMENT_METHOD_SID
----------------------------------------------------------------------------------
WHERE   FLOOR(T.DATE_SID / 10000) IN (YEAR(CURRENT_DATE), YEAR(CURRENT_DATE) - 1)
	AND T44.LEVEL05_CODE='0P111'
	AND CO.COMPANY_CODE_PIS = '9110'
	AND SCENARIO = 'P'
	AND VERSION =1
	AND STATUS ='C'