use database dwh_prod;

SELECT pch.PROFIT_CENTER_SID, ur.USERNAME,  ur.AREA, ur.SUB_AREA, 
LEVEL01_CODE, LEVEL01_NAME,
LEVEL02_CODE, LEVEL02_NAME,
LEVEL03_CODE, LEVEL03_NAME,
LEVEL04_CODE, LEVEL04_NAME,
LEVEL05_CODE, LEVEL05_NAME,
LEVEL06_CODE, LEVEL06_NAME,
LEVEL07_CODE, LEVEL07_NAME
--MDM_USER_RIGHTS_SID, COMPANY, USERNAME, AREA, SUB_AREA, KEY_A, KEY_B, KEY_C, KEY_D, KEY_E, KEY_F, KEY_G, ID, DESCRIPTION, EFF_FM_DT, EFF_TO_DT, MODIFIER, MODIFIED_AT 
--FROM aplsdb.d_profit_center_hierarchy pch
FROM aplsdb.v_profit_center_bi pch
inner join aplsdb.MDM_USER_RIGHTS ur on key_A in (LEVEL01_EXT_REFR, LEVEL02_EXT_REFR,LEVEL03_EXT_REFR,LEVEL04_EXT_REFR,LEVEL05_EXT_REFR,LEVEL06_EXT_REFR,LEVEL07_EXT_REFR,LEVEL08_EXT_REFR,LEVEL09_EXT_REFR,LEVEL10_EXT_REFR)
--                                        and HIERARCHY_EXT_REFR = 'PC|STD_SAP_PIS'
                                        and HIERARCHY_EXT_REFR = 'PC|PIS'
where AREA = 'PR'  AND SUB_AREA = 'MP'
AND USERNAME = 'SSITPS'
and '2302|PIS' in (LEVEL01_EXT_REFR, LEVEL02_EXT_REFR,LEVEL03_EXT_REFR,LEVEL04_EXT_REFR,LEVEL05_EXT_REFR,LEVEL06_EXT_REFR,LEVEL07_EXT_REFR,LEVEL08_EXT_REFR,LEVEL09_EXT_REFR,LEVEL10_EXT_REFR)
and 
case 
when '2302|PIS' = LEVEL01_EXT_REFR then LEVEL02_EXT_REFR = 'N/A'
when '2302|PIS' = LEVEL02_EXT_REFR then LEVEL03_EXT_REFR = 'N/A'
when '2302|PIS' = LEVEL03_EXT_REFR then LEVEL04_EXT_REFR = 'N/A'
when '2302|PIS' = LEVEL04_EXT_REFR then LEVEL05_EXT_REFR = 'N/A'
when '2302|PIS' = LEVEL05_EXT_REFR then LEVEL06_EXT_REFR = 'N/A'
when '2302|PIS' = LEVEL06_EXT_REFR then LEVEL07_EXT_REFR = 'N/A'
when '2302|PIS' = LEVEL07_EXT_REFR then LEVEL08_EXT_REFR = 'N/A'
when '2302|PIS' = LEVEL08_EXT_REFR then LEVEL09_EXT_REFR = 'N/A'
when '2302|PIS' = LEVEL09_EXT_REFR then LEVEL10_EXT_REFR = 'N/A'
end

;
union all
;
SELECT pch.PROFIT_CENTER_SID, ur.USERNAME,  ur.AREA, ur.SUB_AREA, 
LEVEL01_CODE, LEVEL01_NAME,
LEVEL02_CODE, LEVEL02_NAME,
LEVEL03_CODE, LEVEL03_NAME,
LEVEL04_CODE, LEVEL04_NAME,
LEVEL05_CODE, LEVEL05_NAME,
LEVEL06_CODE, LEVEL06_NAME,
LEVEL07_CODE, LEVEL07_NAME
--MDM_USER_RIGHTS_SID, COMPANY, USERNAME, AREA, SUB_AREA, KEY_A, KEY_B, KEY_C, KEY_D, KEY_E, KEY_F, KEY_G, ID, DESCRIPTION, EFF_FM_DT, EFF_TO_DT, MODIFIER, MODIFIED_AT 
--FROM aplsdb.d_profit_center_hierarchy pch
FROM aplsdb.v_profit_center_bi pch
inner join aplsdb.MDM_USER_RIGHTS ur on key_A in (LEVEL01_EXT_REFR, LEVEL02_EXT_REFR,LEVEL03_EXT_REFR,LEVEL04_EXT_REFR,LEVEL05_EXT_REFR,LEVEL06_EXT_REFR,LEVEL07_EXT_REFR,LEVEL08_EXT_REFR,LEVEL09_EXT_REFR,LEVEL10_EXT_REFR)
--                                        and HIERARCHY_EXT_REFR = 'PC|STD_SAP_PIS'
                                        and HIERARCHY_EXT_REFR = 'PC|STD_SAP_PIS'
where AREA = 'PR'  AND SUB_AREA = 'MP'
AND USERNAME = 'SSITPS'
and '0000101105|SAP' in (LEVEL01_EXT_REFR, LEVEL02_EXT_REFR,LEVEL03_EXT_REFR,LEVEL04_EXT_REFR,LEVEL05_EXT_REFR,LEVEL06_EXT_REFR,LEVEL07_EXT_REFR,LEVEL08_EXT_REFR,LEVEL09_EXT_REFR,LEVEL10_EXT_REFR)
and 
case 
when '0000101105|SAP' = LEVEL01_EXT_REFR then LEVEL02_EXT_REFR = 'N/A'
when '0000101105|SAP' = LEVEL02_EXT_REFR then LEVEL03_EXT_REFR = 'N/A'
when '0000101105|SAP' = LEVEL03_EXT_REFR then LEVEL04_EXT_REFR = 'N/A'
when '0000101105|SAP' = LEVEL04_EXT_REFR then LEVEL05_EXT_REFR = 'N/A'
when '0000101105|SAP' = LEVEL05_EXT_REFR then LEVEL06_EXT_REFR = 'N/A'
when '0000101105|SAP' = LEVEL06_EXT_REFR then LEVEL07_EXT_REFR = 'N/A'
when '0000101105|SAP' = LEVEL07_EXT_REFR then LEVEL08_EXT_REFR = 'N/A'
when '0000101105|SAP' = LEVEL08_EXT_REFR then LEVEL09_EXT_REFR = 'N/A'
when '0000101105|SAP' = LEVEL09_EXT_REFR then LEVEL10_EXT_REFR = 'N/A'
end
;
