SELECT pch.PROFIT_CENTER_SID, ur.USERNAME,  ur.AREA, ur.SUB_AREA, 
LEVEL01_CODE, LEVEL01_NAME,
LEVEL02_CODE, LEVEL02_NAME,
LEVEL03_CODE, LEVEL03_NAME,
LEVEL04_CODE, LEVEL04_NAME,
LEVEL05_CODE, LEVEL05_NAME,
LEVEL06_CODE, LEVEL06_NAME,
LEVEL07_CODE, LEVEL07_NAME
FROM aplsdb.v_profit_center_bi pch
inner join aplsdb.MDM_USER_RIGHTS ur on key_A in (LEVEL01_EXT_REFR, LEVEL02_EXT_REFR,LEVEL03_EXT_REFR,LEVEL04_EXT_REFR,LEVEL05_EXT_REFR,LEVEL06_EXT_REFR,LEVEL07_EXT_REFR,LEVEL08_EXT_REFR,LEVEL09_EXT_REFR,LEVEL10_EXT_REFR)
                                        and HIERARCHY_EXT_REFR = 'PC|PIS'
where AREA = 'PR'  AND SUB_AREA = 'MP'
AND USERNAME = #sq($account.personalInfo.userName)#
and  #prompt('pProfitCenter')# in (LEVEL01_EXT_REFR, LEVEL02_EXT_REFR,LEVEL03_EXT_REFR,LEVEL04_EXT_REFR,LEVEL05_EXT_REFR,LEVEL06_EXT_REFR,LEVEL07_EXT_REFR,LEVEL08_EXT_REFR,LEVEL09_EXT_REFR,LEVEL10_EXT_REFR)
and 
case 
when #prompt('pProfitCenter')# = LEVEL01_EXT_REFR then LEVEL02_EXT_REFR = 'N/A'
when #prompt('pProfitCenter')# = LEVEL02_EXT_REFR then LEVEL03_EXT_REFR = 'N/A'
when #prompt('pProfitCenter')# = LEVEL03_EXT_REFR then LEVEL04_EXT_REFR = 'N/A'
when #prompt('pProfitCenter')# = LEVEL04_EXT_REFR then LEVEL05_EXT_REFR = 'N/A'
when #prompt('pProfitCenter')# = LEVEL05_EXT_REFR then LEVEL06_EXT_REFR = 'N/A'
when #prompt('pProfitCenter')# = LEVEL06_EXT_REFR then LEVEL07_EXT_REFR = 'N/A'
when #prompt('pProfitCenter')# = LEVEL07_EXT_REFR then LEVEL08_EXT_REFR = 'N/A'
when #prompt('pProfitCenter')# = LEVEL08_EXT_REFR then LEVEL09_EXT_REFR = 'N/A'
when #prompt('pProfitCenter')# = LEVEL09_EXT_REFR then LEVEL10_EXT_REFR = 'N/A'
end

union all

SELECT pch.PROFIT_CENTER_SID, ur.USERNAME,  ur.AREA, ur.SUB_AREA, 
LEVEL01_CODE, LEVEL01_NAME,
LEVEL02_CODE, LEVEL02_NAME,
LEVEL03_CODE, LEVEL03_NAME,
LEVEL04_CODE, LEVEL04_NAME,
LEVEL05_CODE, LEVEL05_NAME,
LEVEL06_CODE, LEVEL06_NAME,
LEVEL07_CODE, LEVEL07_NAME
FROM aplsdb.v_profit_center_bi pch
inner join aplsdb.MDM_USER_RIGHTS ur on key_A in (LEVEL01_EXT_REFR, LEVEL02_EXT_REFR,LEVEL03_EXT_REFR,LEVEL04_EXT_REFR,LEVEL05_EXT_REFR,LEVEL06_EXT_REFR,LEVEL07_EXT_REFR,LEVEL08_EXT_REFR,LEVEL09_EXT_REFR,LEVEL10_EXT_REFR)
                                        and HIERARCHY_EXT_REFR = 'PC|STD_SAP_PIS'
where AREA = 'PR'  AND SUB_AREA = 'MP'
AND USERNAME = #sq($account.personalInfo.userName)#
and #prompt('pProfitCenter')# in (LEVEL01_EXT_REFR, LEVEL02_EXT_REFR,LEVEL03_EXT_REFR,LEVEL04_EXT_REFR,LEVEL05_EXT_REFR,LEVEL06_EXT_REFR,LEVEL07_EXT_REFR,LEVEL08_EXT_REFR,LEVEL09_EXT_REFR,LEVEL10_EXT_REFR)
and 
case 
when #prompt('pProfitCenter')# = LEVEL01_EXT_REFR then LEVEL02_EXT_REFR = 'N/A'
when #prompt('pProfitCenter')# = LEVEL02_EXT_REFR then LEVEL03_EXT_REFR = 'N/A'
when #prompt('pProfitCenter')# = LEVEL03_EXT_REFR then LEVEL04_EXT_REFR = 'N/A'
when #prompt('pProfitCenter')# = LEVEL04_EXT_REFR then LEVEL05_EXT_REFR = 'N/A'
when #prompt('pProfitCenter')# = LEVEL05_EXT_REFR then LEVEL06_EXT_REFR = 'N/A'
when #prompt('pProfitCenter')# = LEVEL06_EXT_REFR then LEVEL07_EXT_REFR = 'N/A'
when #prompt('pProfitCenter')# = LEVEL07_EXT_REFR then LEVEL08_EXT_REFR = 'N/A'
when #prompt('pProfitCenter')# = LEVEL08_EXT_REFR then LEVEL09_EXT_REFR = 'N/A'
when #prompt('pProfitCenter')# = LEVEL09_EXT_REFR then LEVEL10_EXT_REFR = 'N/A'
end
